[theme]
primaryColor = "#D67C31"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 1

[browser]
gatherUsageStats = false
